version: "3.7"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  worker:
    volumes:
      - ./src/worker:/worker
    build: ./src/worker/.
    command: python3 main.py
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    stdin_open: true
    tty: true
  consumer:
    volumes:
      - ./src/consumer:/consumer
    build: ./src/consumer/.
    depends_on:
      - kafka
    command: python3 main.py
    stdin_open: true
    tty: true
  # elasticsearch:
  #   image: "docker.elastic.co/elasticsearch/elasticsearch:8.1.0"
  #   environment:
  #     discovery.type: "single-node"
  #     cluster.name: "cluster-1"
  #     node.name: "node-1"
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - "./tmp/elasticsearch/data:/usr/share/elasticsearch/data"
